#!/usr/bin/python3

import os
import json

from lib import api

credentials = {
    'dev_id': os.getenv('PTV_USER_ID'),
    'api_key': os.getenv('PTV_API_KEY')
}
client = api.Client(**credentials)

print(client.status_check())
print(client.route_types())
print(client.train_routes_by_name('Craigieburn'))
print(client.stops(route_id=3, route_type=0))
d = client.disruptions()
print(json.dumps(d, indent=2))
for typ, l in d['disruptions'].items():
    print(typ, len(l))

# print(client.train_stops_by_name('Glenbervie'))
# lat=-37.751237
# lon=144.918302
# print(api.stop_list(lat, lon, **credentials))

