#!/usr/bin/env python3

import os
from argparse import ArgumentParser

from lib import api

def run(args):
    credentials = {
        'dev_id': os.getenv('PTV_USER_ID'),
        'api_key': os.getenv('PTV_API_KEY')
    }
    client = api.Client(**credentials)

# print(client.search_train_routes_by_name('Craigieburn'))
# print(client.train_stops_by_name('Glenbervie', 3, 0))
# print(client.departures(0, 1071))
# print(client.departures_for_route())

# print(client.status_check())
# print(client.route_types())
result = client.departures_for_stop_name(0, 'Sandringham', 'Balaclava')
print(result.scheduled_departure_utc)

print(json.dumps(result._asdict(), indent=2))

if __name__ == '__main__':
    parser = ArgumentParser(prog='ptv-cli')

    parser.add_argument('endpoint', action='store', help='endpoint')

    subparsers = parser.add_subparsers(help='operation help')
    parser.add_argument('action', type=str, action='store', help='list')

    args = parser.parse_args()
    print(args)
    run(args)

